# alias l 'eza -lah'
# alias la 'eza -lAh'
# alias ll 'eza -lh'
# alias ls 'eza -G'
# alias lsa 'eza -lah'
alias oc 'opencode'
alias lzd 'lazydocker'
alias vim 'nvim'

# Git aliases (oh-my-zsh style)
alias g 'git'
alias ga 'git add'
alias gaa 'git add --all'
alias gb 'git branch'
alias gba 'git branch -a'
alias gbd 'git branch -d'
alias gco 'git checkout'
alias gcb 'git checkout -b'
alias gc 'git commit -v'
alias gca 'git commit -v -a'
alias gcam 'git commit -a -m'
alias gd 'git diff'
alias gdc 'git diff --cached'
alias gl 'git pull'
alias gp 'git push'
alias gst 'git status'

abbr -a zshconfig 'zed ~/.zshrc'
abbr -a fishconfig 'zed ~/.config/fish/config.fish'
